import type {
  User,
  Tecnico,
  Solicitud,
  Mensaje,
  Pago,
  ServicioPopular,
  EstadisticasTecnico,
  Notificacion,
} from './types';

// ============================================================
// DATOS MOCK TIPADOS
// ============================================================

export const mockCliente: User = {
  id: 'cliente-001',
  nombre: 'María',
  apellido: 'González',
  email: 'maria@example.com',
  telefono: '+52 55 1234 5678',
  rol: 'cliente',
  creadoEn: '2024-01-15T10:00:00Z',
};

export const mockTecnico: Tecnico = {
  id: 'tecnico-001',
  nombre: 'Carlos',
  apellido: 'Ramírez',
  email: 'carlos@example.com',
  telefono: '+52 55 9876 5432',
  rol: 'tecnico',
  especialidad: 'Plomería',
  calificacion: 4.8,
  totalValoraciones: 127,
  disponible: true,
  distanciaKm: 1.2,
  precioBase: 350,
  descripcion:
    'Plomero certificado con 10 años de experiencia. Especialista en tuberías, grifos y calentadores de agua.',
  trabajosCompletados: 312,
  esMaestro: true,
  creadoEn: '2023-03-10T08:00:00Z',
};

export const mockTecnicos: Tecnico[] = [
  mockTecnico,
  {
    id: 'tecnico-002',
    nombre: 'Luis',
    apellido: 'Martínez',
    email: 'luis@example.com',
    rol: 'tecnico',
    especialidad: 'Electricidad',
    calificacion: 4.6,
    totalValoraciones: 89,
    disponible: true,
    distanciaKm: 2.5,
    precioBase: 450,
    descripcion:
      'Electricista certificado. Instalaciones, reparaciones y paneles eléctricos.',
    trabajosCompletados: 201,
    esMaestro: false,
    creadoEn: '2023-05-20T09:00:00Z',
  },
  {
    id: 'tecnico-003',
    nombre: 'Ana',
    apellido: 'Pérez',
    email: 'ana@example.com',
    rol: 'tecnico',
    especialidad: 'Carpintería',
    calificacion: 4.9,
    totalValoraciones: 204,
    disponible: false,
    distanciaKm: 3.1,
    precioBase: 400,
    descripcion: 'Carpintera experta en muebles, pisos y puertas.',
    trabajosCompletados: 450,
    esMaestro: true,
    creadoEn: '2022-11-05T07:00:00Z',
  },
  {
    id: 'tecnico-004',
    nombre: 'Pedro',
    apellido: 'Sánchez',
    email: 'pedro@example.com',
    rol: 'tecnico',
    especialidad: 'Pintura',
    calificacion: 4.3,
    totalValoraciones: 56,
    disponible: true,
    distanciaKm: 0.8,
    precioBase: 300,
    descripcion:
      'Pintor profesional interior y exterior. Presupuesto sin cargo.',
    trabajosCompletados: 89,
    esMaestro: false,
    creadoEn: '2024-02-01T11:00:00Z',
  },
  {
    id: 'tecnico-005',
    nombre: 'Sofía',
    apellido: 'Torres',
    email: 'sofia@example.com',
    rol: 'tecnico',
    especialidad: 'Refrigeración',
    calificacion: 4.7,
    totalValoraciones: 143,
    disponible: true,
    distanciaKm: 1.9,
    precioBase: 550,
    descripcion: 'Técnica en aire acondicionado y refrigeración. Certificada por fabricante.',
    trabajosCompletados: 267,
    esMaestro: true,
    creadoEn: '2023-01-12T10:00:00Z',
  },
];

export const mockSolicitudes: Solicitud[] = [
  {
    id: 'sol-001',
    clienteId: 'cliente-001',
    clienteNombre: 'María González',
    tecnicoId: 'tecnico-001',
    tecnico: mockTecnico,
    categoria: 'plomeria',
    urgencia: 'urgente',
    descripcion:
      'Fuga de agua en el baño principal, la tubería bajo el lavamanos está rota y hay agua en el piso.',
    direccion: 'Calle 123, Colonia Centro, Ciudad de México',
    latitud: 19.4326,
    longitud: -99.1332,
    estado: 'en_progreso',
    presupuestoEstimado: 850,
    creadoEn: '2024-01-20T09:00:00Z',
    actualizadoEn: '2024-01-20T10:30:00Z',
  },
  {
    id: 'sol-002',
    clienteId: 'cliente-001',
    clienteNombre: 'María González',
    categoria: 'electricidad',
    urgencia: 'normal',
    descripcion: 'Instalar 3 enchufes adicionales en la sala de estar.',
    direccion: 'Calle 123, Colonia Centro, Ciudad de México',
    estado: 'pendiente',
    creadoEn: '2024-01-22T14:00:00Z',
    actualizadoEn: '2024-01-22T14:00:00Z',
  },
  {
    id: 'sol-003',
    clienteId: 'cliente-001',
    clienteNombre: 'María González',
    tecnicoId: 'tecnico-002',
    categoria: 'electricidad',
    urgencia: 'urgente',
    descripcion: 'Sin luz en la cocina, interruptor dañado.',
    direccion: 'Av. Reforma 456, CDMX',
    estado: 'completada',
    presupuestoEstimado: 450,
    creadoEn: '2024-01-10T08:00:00Z',
    actualizadoEn: '2024-01-10T12:00:00Z',
  },
];

export const mockSolicitudesDisponibles: Solicitud[] = [
  {
    id: 'sol-010',
    clienteId: 'cliente-010',
    clienteNombre: 'Roberto Díaz',
    categoria: 'plomeria',
    urgencia: 'urgente',
    descripcion: 'Tubería reventada en cocina, necesito atención inmediata.',
    direccion: 'Col. Narvarte, CDMX',
    estado: 'pendiente',
    presupuestoEstimado: 600,
    creadoEn: new Date(Date.now() - 15 * 60000).toISOString(),
    actualizadoEn: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'sol-011',
    clienteId: 'cliente-011',
    clienteNombre: 'Carmen López',
    categoria: 'plomeria',
    urgencia: 'normal',
    descripcion: 'Cambio de llaves de paso en baño y cocina.',
    direccion: 'Col. Del Valle, CDMX',
    estado: 'pendiente',
    presupuestoEstimado: 400,
    creadoEn: new Date(Date.now() - 45 * 60000).toISOString(),
    actualizadoEn: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: 'sol-012',
    clienteId: 'cliente-012',
    clienteNombre: 'Jorge Mendoza',
    categoria: 'plomeria',
    urgencia: 'normal',
    descripcion: 'El calentador de agua no enciende. Revisar conexiones.',
    direccion: 'Col. Roma Norte, CDMX',
    estado: 'pendiente',
    presupuestoEstimado: 500,
    creadoEn: new Date(Date.now() - 2 * 3600000).toISOString(),
    actualizadoEn: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
];

export const mockMensajes: Mensaje[] = [
  {
    id: 'msg-001',
    solicitudId: 'sol-001',
    remitenteId: 'tecnico-001',
    remitenteNombre: 'Carlos Ramírez',
    esCliente: false,
    texto: 'Hola María, estoy en camino. Llegaré en aproximadamente 15 minutos.',
    creadoEn: '2024-01-20T10:00:00Z',
  },
  {
    id: 'msg-002',
    solicitudId: 'sol-001',
    remitenteId: 'cliente-001',
    remitenteNombre: 'María González',
    esCliente: true,
    texto: 'Perfecto, te espero. El departamento es el 4B.',
    creadoEn: '2024-01-20T10:02:00Z',
  },
  {
    id: 'msg-003',
    solicitudId: 'sol-001',
    remitenteId: 'tecnico-001',
    remitenteNombre: 'Carlos Ramírez',
    esCliente: false,
    texto: 'Gracias, ya voy subiendo. Traigo todo el material necesario.',
    creadoEn: '2024-01-20T10:15:00Z',
  },
  {
    id: 'msg-004',
    solicitudId: 'sol-001',
    remitenteId: 'cliente-001',
    remitenteNombre: 'María González',
    esCliente: true,
    texto: '¿Cuánto tiempo crees que tarde el trabajo?',
    creadoEn: '2024-01-20T10:20:00Z',
  },
  {
    id: 'msg-005',
    solicitudId: 'sol-001',
    remitenteId: 'tecnico-001',
    remitenteNombre: 'Carlos Ramírez',
    esCliente: false,
    texto: 'Calculo unos 45 minutos si la fuga es solo en el conector. Si hay que cambiar más tubería podría ser 1.5 horas.',
    creadoEn: '2024-01-20T10:22:00Z',
  },
];

export const mockPago: Pago = {
  id: 'pago-001',
  solicitudId: 'sol-001',
  clienteId: 'cliente-001',
  tecnicoId: 'tecnico-001',
  monto: 850,
  metodoPago: 'tarjeta',
  estado: 'pendiente',
  descripcion:
    'Reparación de tubería en baño principal — Material + mano de obra',
  creadoEn: '2024-01-20T12:00:00Z',
};

export const mockServiciosPopulares: ServicioPopular[] = [
  {
    id: 'sv-01',
    nombre: 'Plomería',
    categoria: 'plomeria',
    emoji: '🔧',
    descripcion: 'Fugas, tuberías y más',
    precioDesde: 350,
  },
  {
    id: 'sv-02',
    nombre: 'Electricidad',
    categoria: 'electricidad',
    emoji: '⚡',
    descripcion: 'Instalaciones y reparaciones',
    precioDesde: 450,
  },
  {
    id: 'sv-03',
    nombre: 'Carpintería',
    categoria: 'carpinteria',
    emoji: '🪵',
    descripcion: 'Muebles, puertas y pisos',
    precioDesde: 400,
  },
  {
    id: 'sv-04',
    nombre: 'Pintura',
    categoria: 'pintura',
    emoji: '🎨',
    descripcion: 'Interior y exterior',
    precioDesde: 300,
  },
  {
    id: 'sv-05',
    nombre: 'Cerrajería',
    categoria: 'cerrajeria',
    emoji: '🔑',
    descripcion: 'Cambio y apertura de cerraduras',
    precioDesde: 250,
  },
  {
    id: 'sv-06',
    nombre: 'Limpieza',
    categoria: 'limpieza',
    emoji: '🧹',
    descripcion: 'Limpieza profunda del hogar',
    precioDesde: 200,
  },
  {
    id: 'sv-07',
    nombre: 'Jardinería',
    categoria: 'jardineria',
    emoji: '🌿',
    descripcion: 'Poda, riego y diseño',
    precioDesde: 250,
  },
  {
    id: 'sv-08',
    nombre: 'Refrigeración',
    categoria: 'refrigeracion',
    emoji: '❄️',
    descripcion: 'Aire acondicionado y refrigeradores',
    precioDesde: 550,
  },
];

export const mockEstadisticas: EstadisticasTecnico = {
  trabajosHoy: 3,
  gananciasSemana: 4850,
  calificacion: 4.8,
  trabajosCompletados: 312,
  gananciasPorDia: [
    { dia: 'Lun', monto: 850 },
    { dia: 'Mar', monto: 600 },
    { dia: 'Mié', monto: 1200 },
    { dia: 'Jue', monto: 450 },
    { dia: 'Vie', monto: 950 },
    { dia: 'Sáb', monto: 800 },
    { dia: 'Dom', monto: 0 },
  ],
};

export const mockNotificaciones: Notificacion[] = [
  {
    id: 'not-001',
    titulo: 'Tu técnico va en camino',
    detalle: 'Carlos Ramírez llegará en aproximadamente 15 minutos.',
    creadoEn: new Date(Date.now() - 5 * 60000).toISOString(),
    leida: false,
  },
  {
    id: 'not-002',
    titulo: 'Nuevo mensaje',
    detalle: 'Tienes un mensaje nuevo sobre tu servicio de plomería.',
    creadoEn: new Date(Date.now() - 40 * 60000).toISOString(),
    leida: false,
  },
  {
    id: 'not-003',
    titulo: 'Pago confirmado',
    detalle: 'Recibimos el pago de tu servicio de electricidad.',
    creadoEn: new Date(Date.now() - 26 * 3600000).toISOString(),
    leida: true,
  },
];
